### ISSUE TITLE
Old grains cannot be cloned after upgrade

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/gitlab-sandstorm#10]
I have been using the gitlab sandstorm package for quite a time. Now I updated the app and when following the instructions to clone the repo I always get:

```
Cloning into 'repo_lmsygsik_RENAME_ME'...
fatal: repository 'https://l******k@api.server.com/gitlab/repo.git/' not found
```

When I create a new grain it is working. But not with the updated grains. Any idea how to fix that?

**Comment by JamborJan** [comment]
The `not found`issue is related to the fact that my old repos had all own names. Unfortunately changing the name in the command does not help. I get a `remote: Error: Invalid authorization token [403]`error then.

**Comment by JamborJan** [comment]
Seems to be the same as this: Repo name change breaks repo #7 

Closed this issue and follow the existing one.

**Comment by xet7** [comment]
This issue was moved to sandstormports/gitlab-sandstorm#6
