### ISSUE TITLE
error 500 on "blame" feature

### ISSUE THREAD

**Issue by zeigerpuppy** [dwrensha/gitlab-sandstorm#16]
I've created a file, made a couple of commits and tried to use the "blame" feature

But I get error 500

**Comment by dwrensha** [comment]
Thanks for the report. Fixed in https://github.com/dwrensha/gitlab-sandstorm/commit/ed92084404cacc0c5d265f9f8a7efc674718ca86. The new version should show up on the app market shortly.

**Comment by zeigerpuppy** [comment]
Thanks so much for the quick fix!
Tested and working
