### ISSUE TITLE
Linking between wiki pages is impossible and returns an error 500

### ISSUE THREAD

**Issue by Xia0ben** [dwrensha/gitlab-sandstorm#19]
Howdy =) .

First, hats off to you the people who contribute to make Sandstorm the great piece of software it is.

So a little description :
When you write a link between to wiki pages using the markdown syntax [NAME](Url), replacing the "Url" by the target page's slug, and try to save by clicking on the "Save changes" button, Gitlab goes kaboom! and returns an error 500. Refreshing and trying again does not change a thing.

This problem exists not only on my own server, but also on the sandstorm.io demo (so we are talking about the latest versions of both Sandstorm and the GitLab app here).

Thanks for your already great work, and hope you will get some time to investigate the problem ;-).

EDIT : Just tried to clone, make the same modification offline and pull push the wiki's data : when you try to open the modified wiki page, it goes error 500 too.
External links do not cause this problem, however the link does not work on simple click (gotta right-click and open in new tab), which is a little bit impractical.

**Comment by dwrensha** [comment]
Thanks for the report!

Fixed in [this commit](https://github.com/dwrensha/gitlabhq/commit/e087c8f2439124091278b4ea928e48535c63a57b).

I've pushed a new release to the [app market](https://apps.sandstorm.io/app/zx9d3pt0fjh4uqrprjftgpqfwgzp6y2ena6098ug3ctv37uv6kfh).

**Comment by Xia0ben** [comment]
Wow, that was fast ! Works like a charm now. Thanks ;-).
