### ISSUE TITLE
500 error on bulk update of issues in repo

### ISSUE THREAD

**Issue by erikmaarten** [dwrensha/gitlab-sandstorm#3]
It seems the page redirection when bulk updating is missing an redirection link. Carrying out a bulk update seems to work, but redirects to 500 error page.

To reproduce:
1. Select a few issues in a repo
2. Select a milestone in the drop-down list
3. Click "Update issues"

```
I, [2015-08-08T22:31:28.415194 #9]  INFO -- : Started POST "/gitlab/repo/issues/bulk_update" for 127.0.0.1 at 2015-08-08 22:31:28 +0000
I, [2015-08-08T22:31:28.417405 #9]  INFO -- : Processing by Projects::IssuesController#bulk_update as HTML
I, [2015-08-08T22:31:28.417516 #9]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[manually removed for bug report]", "update"=>{"status"=>"", "assignee_id"=>"", "milestone_id"=>"1", "issues_ids"=>"21,20,15,11,7"}, "status"=>"", "project_id"=>"gitlab/repo"}
I, [2015-08-08T22:31:28.525513 #9]  INFO -- : Redirected to 
I, [2015-08-08T22:31:28.525742 #9]  INFO -- : Completed 500 Internal Server Error in 108ms
F, [2015-08-08T22:31:28.527260 #9] FATAL -- : 
ActionController::RedirectBackError (No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].):
  app/controllers/projects/issues_controller.rb:97:in `bulk_update'
```

**Comment by dwrensha** [comment]
Hm. This looks like another instance of https://gitlab.com/gitlab-org/gitlab-ce/issues/1066. (Please consider commenting on that issue too, because if this gets fixed upstream that means less work for me.) I thought that I had fixed all instances of this, but apparently I missed one.

**Comment by dwrensha** [comment]
Nice, it looks like this is fixed upstream: https://gitlab.com/gitlab-org/gitlab-ce/issues/1066

**Comment by dwrensha** [comment]
Fixed in the release that I just published: https://apps.sandstorm.io/app/zx9d3pt0fjh4uqrprjftgpqfwgzp6y2ena6098ug3ctv37uv6kfh
