### ISSUE TITLE
URLs don't propagate to the browser location hash

### ISSUE THREAD

**Issue by ghost** [dwrensha/gitlab-sandstorm#5]
Click around inside a GitLab instance within sandstorm and the URL bar doesn't update with the location hash. Expected to see it update with something like:

https://site.sandstorm.io/grain/LfTnLWo6ETxW9ERHB6bhkE#/gitlab/repo/commits/master

Similar to what the [Lychee port](https://github.com/jparyani/Lychee) does.

**Comment by dwrensha** [comment]
I agree that this would be nice! I didn't get around to adding this feature in my latest release, but hopefully I will next time.

**Comment by dwrensha** [comment]
Fixed in the release that I just published: https://apps.sandstorm.io/app/zx9d3pt0fjh4uqrprjftgpqfwgzp6y2ena6098ug3ctv37uv6kfh
