### ISSUE TITLE
Can't assign issues to users

### ISSUE THREAD

**Issue by ghost** [dwrensha/gitlab-sandstorm#6]
Steps:
- Click "Issues" on the sidebar"
- Click "New issue"
- Click the "Assign to" dropdown
- The dropdown just says "searching" forever and never displays a list of users

**Comment by dwrensha** [comment]
Thanks! This is fixed in the latest release: https://apps.sandstorm.io/app/zx9d3pt0fjh4uqrprjftgpqfwgzp6y2ena6098ug3ctv37uv6kfh
